pipeline:
  build:
    image: golang
    commands:
#      - go get
      - go build
      - go test -v

  notify:
    image: plugins/drone-slack
    webhook_url: https://hooks.slack.com/services/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
    channel: drone-test
    username: aki
    when:
      status: [ success, failure ]
#      image: drillster/drone-email
#      from: takano@acmos.jp
#      host: mailredirector.newbiz.acmos.jp
#      port: 25001
#      skip_verify: true
##      recipients:
##        - takano@acmos.jp
#      when:
#       push: acmos-takano
##        status: [ success, failure ]
