pipeline:
  build:
    image: golang
    commands:
#      - go get
      - go build
      - go test -v

  notify:
      image: drillster/drone-email
      from: takano@acmos.jp
      host: mailredirector.newbiz.acmos.jp
      port: 25001
      skip_verify: true
#      recipients:
#        - takano@acmos.jp
      when:
        push: acmos-takano
#        status: [ success, failure ]
