pipeline:
  build:
    image: golang
    environment:
      GOPATH: $HOME
      GOBIN: $GOPATH/bin
    commands:
      - echo $HOME
      - echo $GOPATH
      - go get
      - sleep 10
      - go build
      - go test -v

  notify:
#    image: plugins/drone-slack
#    image: plugins/slack
#    webhook: https://hooks.slack.com/services/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
#    username: incoming-webhook
#    when:
#      status: [ success, failure ]
    image: drillster/drone-email
    from: takano@acmos.jp
    host: mailredirector.newbiz.acmos.jp
    port: 25001
    skip_verify: true
#      recipients:
#        - takano@acmos.jp
#      when:
#       push: acmos-takano
#        status: [ success, failure ]
#

services:
   database:
     image: tmtcloud_pgsql
     environment:
       # DB,USER,PASSWORDまではマスター、ビルド用共通設定
       # MASTERHOSTはビルド専用パラメータ。コピー元となるマスタDBのIPもしくは認識できるホスト名
       # MASTERPORTは上記のポート番号
       POSTGRES_DB: tmt_cloud
       POSTGRES_USER: pguser
       POSTGRES_PASSWORD: tGTAtck-DetaBesu5
       POSTGRES_MASTERHOST: docker2-with-compose
       POSTGRES_MASTERPORT: 5432
       # 「command」は一応反応するが何故か/bin/bashが無いと言われるし
       # Postgreコンテナとして取り込んだ初期起動sqlを上書きする模様
    #  command:
    #    - echo "aaabbbccc"
    #  command: set
